/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cursoemvideo.soma;

/**
 *
 * @author computador
 */
public class TelaSoma extends javax.swing.JFrame {

    /**
     * Creates new form TelaSoma
     */
    public TelaSoma() {
        initComponents();
        panResultado.setVisible(false);         //  Esconde Painel de resultados
        panErro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValor = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        panErro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panResultado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResto = new javax.swing.JLabel();
        lblPow = new javax.swing.JLabel();
        lblRaiz2 = new javax.swing.JLabel();
        lblRaiz3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAbs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 29, 65, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 29, -1, -1));

        panErro.setBackground(new java.awt.Color(255, 255, 0));
        panErro.setForeground(new java.awt.Color(204, 204, 0));
        panErro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Erro! Valor invalido.");
        panErro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 320, 110));

        getContentPane().add(panErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 140));

        panResultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Raiz Quadrada");
        panResultado.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setText("Raiz Cubica");
        panResultado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel6.setText("Valor Absoluto");
        panResultado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblResto.setText("0");
        panResultado.add(lblResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        lblPow.setText("0");
        panResultado.add(lblPow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lblRaiz2.setText("0");
        panResultado.add(lblRaiz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        lblRaiz3.setText("0");
        panResultado.add(lblRaiz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel2.setText("Resto da divisão por 2");
        panResultado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel3.setText("Valor de potencia");
        panResultado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblAbs.setText("0");
        panResultado.add(lblAbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        getContentPane().add(panResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 350, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String text = txtValor.getText();
        if (text.equals("")){
            panErro.setVisible(true);
            panResultado.setVisible(false);
        }else{
            int valor = Integer.parseInt(txtValor.getText());           //Importa valor

            lblResto.setText(Integer.toString(valor % 2));              //Seta o resto da divisão por 2
            lblPow.setText(Double.toString(Math.pow(valor, 3)));        //Seta Valor elevado ao cubo
            lblRaiz2.setText(String.format("%.2f",Math.sqrt(valor)));   //Seta Raiz quadrada
            lblRaiz3.setText(Double.toString(Math.cbrt(valor)));        //Seta Raiz Cubica
            lblAbs.setText(Integer.toString(Math.abs(valor)));          //Seta Valor Absoluto
             panErro.setVisible(false);
             panResultado.setVisible(true);                              //Torna visivel painel de resultados
        }     
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAbs;
    private javax.swing.JLabel lblPow;
    private javax.swing.JLabel lblRaiz2;
    private javax.swing.JLabel lblRaiz3;
    private javax.swing.JLabel lblResto;
    private javax.swing.JPanel panErro;
    private javax.swing.JPanel panResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
